# Main navigation.
nav:
  - Getting Started:
    - Introduction: index.md
    - Setup: getting-started/index.md
    - Docker Compose: getting-started/docker-compose.md
    - Pure Docker: getting-started/docker.md
    - Raspberry Pi: getting-started/raspberry-pi.md
    - FreeBSD: getting-started/freebsd.md
    - Cloud:
      - DigitalOcean: getting-started/cloud/digitalocean.md
    - NAS Devices:
      - Synology: getting-started/nas/synology.md
      - Unraid: getting-started/nas/unraid.md
    - Config Options: getting-started/config-options.md
    - Getting Updates: getting-started/updates.md
    - Troubleshooting:
      - Checklists: getting-started/troubleshooting/index.md
      - Logs:  getting-started/troubleshooting/logs.md
      - Docker: getting-started/troubleshooting/docker.md
      - MariaDB: getting-started/troubleshooting/mariadb.md
      - Browsers: getting-started/troubleshooting/browsers.md
      - Performance: getting-started/troubleshooting/performance.md
    # - Support: getting-started/support.md
    - Reverse Proxies:
      - Traefik: getting-started/proxies/traefik.md
      - Caddy 1: getting-started/proxies/caddy-1.md
      - Caddy 2: getting-started/proxies/caddy-2.md
      - NGINX: getting-started/proxies/nginx.md
      - Apache 2.4: getting-started/proxies/apache-2.md
      - SWAG: getting-started/proxies/swag.md
    - Advanced:
      - Transcoding: getting-started/advanced/transcoding.md
      - Kubernetes: getting-started/advanced/kubernetes.md
      - Backups: getting-started/advanced/backups.md
      - Databases: getting-started/advanced/databases.md
      - Caching: getting-started/advanced/caching.md
      - NGINX: getting-started/advanced/nginx-proxy-setup.md
      - Scalability: getting-started/advanced/scalability.md
    - FAQ: getting-started/faq.md
  - User Guide:
    - Introduction: user-guide/index.md
    # - Setting up: user-guide/setup.md
    - Library:
      - Introduction: user-guide/library/index.md
      - Index Originals: user-guide/library/originals.md
      - Import Files: user-guide/library/import.md
      - Web Upload: user-guide/library/upload.md
      - WebDAV Sync: user-guide/library/webdav.md
      - File Browser: user-guide/library/files.md
      #- Import from camera: user-guide.md
      #- Import from Facebook: user-guide.md
      #- Import from NAS: user-guide.md
      #- Import from Apple Photos: user-guide.md
      #- Import from One Drive: user-guide.md
    # - Sync and Back Up:
    # - WebDAV Sync
    #    - Nextcloud: user-guide/nextcloud.md
    - Browse & Search:
      - Navigate: user-guide/navigate.md
      - Views: user-guide/organize/views.md
      - Search: user-guide/organize/search.md
      - Sections: user-guide/organize/browse.md
    - Organize:
      - Albums: user-guide/organize/albums.md
      - People: user-guide/organize/people.md
      - Labels: user-guide/organize/labels.md
      - Archive: user-guide/organize/archive.md
      - Delete: user-guide/organize/delete.md
      - Private: user-guide/organize/private.md
      - Review: user-guide/organize/review.md
      - Stacks: user-guide/organize/stacks.md
      - Edit Metadata: user-guide/organize/edit.md
      - Download: user-guide/organize/download.md
      - Videos: user-guide/organize/video.md
      - Places: user-guide/organize/places.md
      - Moments: user-guide/organize/moments.md
      - Calendar: user-guide/organize/calendar.md
      - Folders: user-guide/organize/folders.md
      - Panoramas: user-guide/organize/panoramas.md
      - Scans: user-guide/organize/scans.md
    - Share:
        - Album Link: user-guide/share/share.md
    - Sync:
      - WebDAV: user-guide/sync/webdav.md
      - Mobile Devices: user-guide/sync/mobile-devices.md
      - Dropbox: user-guide/sync/dropbox.md
    - Settings:
      - General: user-guide/settings/general.md
      - Library: user-guide/settings/library.md
      - Advanced: user-guide/settings/advanced.md
      - Sync: user-guide/settings/sync.md
      - Account: user-guide/settings/account.md
      # - Places: user-guide/settings/places.md
    - Migrate:
      - Google Photos: user-guide/use-cases/google.md
      - Apple Photos: user-guide/use-cases/apple.md
      - Flickr: user-guide/use-cases/flickr.md
      #- Link directories from remote:
    - Advanced:
      - Metadata: user-guide/advanced/metadata.md
      - Backups: user-guide/advanced/backups.md
      - Restore: user-guide/advanced/restore.md
      - Export: user-guide/advanced/export.md
      - Folders: user-guide/advanced/folders.md
      #- Commands: user-guide/advanced/commands.md
    - Mobile App (PWA): user-guide/pwa.md
    - Release Notes: release-notes.md
    - FAQ: user-guide/faq.md
  # - Metadata: user-guide/metadata.md
  - Developer Guide:
    - Introduction: developer-guide/index.md
    - GitHub Issues: developer-guide/issues.md
    - Pull Requests: developer-guide/pull-requests.md
    - Code Quality: developer-guide/code-quality.md
    - Setup: developer-guide/setup.md
    - Directories: developer-guide/directories.md
    - Configuration: developer-guide/configuration.md
    - Running Tests: developer-guide/tests.md
    - Documentation: developer-guide/documentation.md
    - Translations:
        - Add Translations: developer-guide/translations-weblate.md
        - Legacy Method: developer-guide/translations.md
    - Security Policy: security-policy.md
    - User Interface:
      - Introduction: developer-guide/ui/introduction.md
      - Screenshots: developer-guide/ui/screenshots.md
      - Components: developer-guide/ui/components.md
      - Design: developer-guide/ui/design.md
      - REST API: developer-guide/ui/rest-api.md
      - Browsers: developer-guide/ui/browsers.md
      - Interactive Maps: developer-guide/ui/maps.md
    - Media Files:
      - Formats: developer-guide/media/index.md
      - Import: developer-guide/media/import.md
      - Abstraction: developer-guide/media/abstraction.md
      - Encryption: developer-guide/media/encryption.md
      - RAW Images: developer-guide/media/raw.md
      - HEIF / HEIC: developer-guide/media/heif.md
      - Videos: developer-guide/media/videos.md
      - Thumbnails: developer-guide/media/thumbnails.md
      - Samples: developer-guide/media/samples.md
    - Metadata:
      - Geocoding: developer-guide/metadata/geocoding.md
      - Color Extraction: developer-guide/metadata/colors.md
      - Image Classification: developer-guide/metadata/classification.md
      - Face Recognition: developer-guide/metadata/face-recognition.md
      - XMP: developer-guide/metadata/xmp.md
      - EXIF: developer-guide/metadata/exif.md
      - Edit EXIF: developer-guide/metadata/edit-exif.md
    - Clients:
      - Go: developer-guide/clients/go.md
    - Checklists:
      - Web Security: developer-guide/checklists/web-security.md
    - Technologies:
      - YAML: developer-guide/technologies/yaml.md
      - Golang: developer-guide/technologies/golang.md
      - TensorFlow: developer-guide/technologies/tensorflow.md
      - Docker: developer-guide/technologies/docker.md
      - Broadway: developer-guide/technologies/broadway.md
      - External APIs: developer-guide/technologies/external-apis.md
  - About:
      - Team: team.md
      - Funding: funding.md
      - Credits: credits.md
      - Contact: contact.md
      - License:
          - GNU AGPL: license/agpl.md
          - Documentation: license/docs.md

extra_css:
  - css/custom.css

# External links.
extra:
  generator: false
  alternate:
    - name: üá¨üáß‚ÄÇEnglish
      link: /
      lang: en
    - name: üá©üá™‚ÄÇDeutsch
      link: https://docs-de.photoprism.app/
      lang: de
  social:
    - icon: fontawesome/brands/github
      link: https://link.photoprism.app/github
    - icon: fontawesome/brands/patreon
      link: https://link.photoprism.app/patreon
    - icon: material/chat
      link: https://link.photoprism.app/chat
    - icon: fontawesome/brands/twitter
      link: https://link.photoprism.app/twitter
    - icon: fontawesome/brands/reddit
      link: https://link.photoprism.app/reddit
    - icon: fontawesome/brands/linkedin
      link: https://link.photoprism.app/linkedin
    - icon: material/home
      link: https://photoprism.app/

# Project paths.
docs_dir: docs
site_dir: site

# Project information.
site_name: PhotoPrism
site_description: User Guide
site_author: PhotoPrism
site_url: https://docs.photoprism.app/

# Repository information.
repo_name: photoprism/photoprism
repo_url: https://github.com/photoprism/photoprism
edit_uri: https://github.com/photoprism/photoprism-docs/tree/master/docs
copyright: 'Made with ‚ù§ in Berlin'

# Theme configuration.
theme:
  name: 'material'
  custom_dir: overrides

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  palette:
    scheme: default
    primary: white
    accent: amber
  font:
    text: Roboto
    code: Roboto Mono
  favicon: icons/favicon.ico
  icon:
    logo: logo

plugins:
  - search

# MkDocs extensions.
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde
  - attr_list
  - abbr
  - md_in_html
