# Main navigation.
nav:
  - Getting Started:
    - Features: index.md
    - Setup: getting-started/index.md
    - Docker Compose: getting-started/docker-compose.md
    - Portainer: getting-started/portainer/index.md
    - Pure Docker: getting-started/docker.md
    - Config Options: getting-started/config-options.md
    - Config Files:
      - options.yml: getting-started/config-files/index.md
      - defaults.yml: getting-started/config-files/defaults.md
      - settings.yml: getting-started/config-files/settings.md
    - Cloud Hosting:
      - PikaPods: getting-started/cloud/pikapods.md
      - DigitalOcean: getting-started/cloud/digitalocean.md
    - Raspberry Pi:
      - Requirements: getting-started/raspberry-pi.md
      - SD Card Image: getting-started/raspberry-pi/microsd-image.md
    - NAS Devices:
      - Asustor: getting-started/nas/asustor.md
      - Synology: getting-started/nas/synology.md
      - QNAP: getting-started/nas/qnap.md
      - Unraid: getting-started/nas/unraid.md
      - OpenMediaVault: getting-started/nas/openmediavault.md
    - BSD Ports:
      - FreeBSD: getting-started/ports/freebsd.md
    - Using a CDN: getting-started/using-a-cdn.md
    - Using HTTPS: getting-started/using-https.md
    - Getting Updates: getting-started/updates.md
    - Troubleshooting:
      - Checklists: getting-started/troubleshooting/index.md
      - Logs:  getting-started/troubleshooting/logs.md
      - Docker: getting-started/troubleshooting/docker.md
      - MariaDB: getting-started/troubleshooting/mariadb.md
      - SQLite: getting-started/troubleshooting/sqlite.md
      - Raspberry Pi: getting-started/troubleshooting/raspberry-pi.md
      - Windows: getting-started/troubleshooting/windows.md
      - Browsers: getting-started/troubleshooting/browsers.md
      - Performance: getting-started/troubleshooting/performance.md
      - Firewall: getting-started/troubleshooting/firewall.md
    # - Support: getting-started/support.md
    - Remote Access:
      - Tailscale VPN: getting-started/vpn/tailscale.md
    - Reverse Proxies:
      - Traefik: getting-started/proxies/traefik.md
      - Caddy 1: getting-started/proxies/caddy-1.md
      - Caddy 2: getting-started/proxies/caddy-2.md
      - NGINX: getting-started/proxies/nginx.md
      - Apache 2.4: getting-started/proxies/apache-2.md
      - SWAG: getting-started/proxies/swag.md
      - Haproxy: getting-started/proxies/haproxy.md
    - Advanced:
      - Video Transcoding: getting-started/advanced/transcoding.md
      - Using Kubernetes: getting-started/advanced/kubernetes.md
      - Docker Security: getting-started/advanced/docker-security.md
      - Docker Volumes: getting-started/advanced/docker-volumes.md
      - Backup Guide: getting-started/advanced/backups.md
      - Database Setup: getting-started/advanced/databases.md
      - Database Migrations:
        - Index Schema: getting-started/advanced/migrations/index.md
        - SQLite to MariaDB: getting-started/advanced/migrations/sqlite-to-mariadb.md
        - MariaDB to SQLite: getting-started/advanced/migrations/mariadb-to-sqlite.md
      - Cache Optimization: getting-started/advanced/caching.md
      - NGINX Proxy Setup: getting-started/advanced/nginx-proxy-setup.md
      - Horizontal Scaling: getting-started/advanced/scalability.md
    - Known Issues: known-issues.md
    - FAQ: getting-started/faq.md
  - User Guide:
    - Installation: user-guide/index.md
    - First Steps üë£: user-guide/first-steps.md
    # - Setting up: user-guide/setup.md
    - Media Library:
      - Overview: user-guide/library/index.md
      - Indexing Originals: user-guide/library/originals.md
      - Import to Originals: user-guide/library/import.md
      - Duplicate Detection: user-guide/library/duplicates.md
      - Metadata Support: user-guide/library/metadata.md
      - Web Upload: user-guide/library/upload.md
      - WebDAV Sync: user-guide/library/webdav.md
      - File Browser: user-guide/library/files.md
      #- Import from camera: user-guide.md
      #- Import from Facebook: user-guide.md
      #- Import from NAS: user-guide.md
      #- Import from Apple Photos: user-guide.md
      #- Import from One Drive: user-guide.md
    # - Sync and Back Up:
    # - WebDAV Sync
    #    - Nextcloud: user-guide/nextcloud.md
    - Finding Pictures:
      - User Interface: user-guide/navigate.md
      - Search Your Library: user-guide/search/index.md
      - Search Result Views: user-guide/search/views.md
      - Search Filters: user-guide/search/filters.md
    - Features:
      - Albums: user-guide/organize/albums.md
      - People: user-guide/organize/people.md
      - Labels: user-guide/organize/labels.md
      - Archive: user-guide/organize/archive.md
      - Delete: user-guide/organize/delete.md
      - Private: user-guide/organize/private.md
      - Review: user-guide/organize/review.md
      - Stacks: user-guide/organize/stacks.md
      - Edit Metadata: user-guide/organize/edit.md
      - Rotate Image: user-guide/organize/rotate.md
      - Download: user-guide/organize/download.md
      - Videos: user-guide/organize/video.md
      - Places: user-guide/organize/places.md
      - Moments: user-guide/organize/moments.md
      - Calendar: user-guide/organize/calendar.md
      - Folders: user-guide/organize/folders.md
      - Panoramas: user-guide/organize/panoramas.md
      - Scans: user-guide/organize/scans.md
    - Sharing:
      - Link Sharing: user-guide/share/index.md
      - With Apps: user-guide/share/services-share.md
    - Settings:
      - General: user-guide/settings/general.md
      - Library: user-guide/settings/library.md
      - Advanced: user-guide/settings/advanced.md
      - Services: user-guide/settings/sync.md
      - Account: user-guide/settings/account.md
    - Remote Sync:
      - WebDAV: user-guide/sync/webdav.md
      - Mobile Devices: user-guide/sync/mobile-devices.md
      - Other Apps: user-guide/sync/services-sync.md
      - Dropbox: user-guide/sync/dropbox.md
    - Backup Guide:
      - Creating Backups: user-guide/backups/index.md
      - Restoring Backups: user-guide/backups/restore.md
      - External Storage: user-guide/backups/external-storage.md
      - Metadata Exports: user-guide/backups/export.md
      - Folder Overview: user-guide/backups/folders.md
      #- Commands: user-guide/advanced/commands.md
    - Cloud Migration:
      - Google Photos: user-guide/use-cases/google.md
      - Apple Photos: user-guide/use-cases/apple.md
      - Flickr: user-guide/use-cases/flickr.md
    - Managing Users:
      - Admin Web UI: user-guide/users/index.md
      - CLI Commands: user-guide/users/cli.md
      - Account Roles: user-guide/users/roles.md
      - Sharing with Guests: user-guide/users/sharing.md
      - Multiple Libraries: user-guide/users/libraries.md
      - Setting Up 2FA: user-guide/users/2fa.md
      - Client Credentials: user-guide/users/client-credentials.md
    - Mobile App (PWA): user-guide/pwa.md
    - Release Notes: release-notes.md
    - FAQ: user-guide/faq.md
  # - Metadata: user-guide/metadata.md
  - Developer Guide:
    - Introduction: developer-guide/index.md
    - Build Setup: developer-guide/setup.md
    - Best Practices: developer-guide/code-quality.md
    - GitHub Issues: developer-guide/issues.md
    - Pull Requests: developer-guide/pull-requests.md
    - Project Structure: developer-guide/directories.md
    - Config Options: developer-guide/configuration.md
    - Running Tests: developer-guide/tests.md
    - Documentation: developer-guide/documentation.md
    - Translations:
      - Using Weblate: developer-guide/translations-weblate.md
      - Legacy Method: developer-guide/translations.md
    - Media Files:
      - File Formats: developer-guide/media/index.md
      - Test Samples: developer-guide/media/samples.md
      - RAW Images: developer-guide/media/raw.md
      - HEIC / HEIF: developer-guide/media/heif.md
      - Videos: developer-guide/media/videos.md
      - Live Photos: developer-guide/media/live.md
      - Thumbnails: developer-guide/media/thumbnails.md
      - File Import: developer-guide/media/import.md
      - Storage: developer-guide/media/storage.md
    - Metadata:
      - Adobe XMP: developer-guide/metadata/xmp.md
      - Exif Extraction: developer-guide/metadata/exif/index.md
      - Editing Exif Data: developer-guide/metadata/exif/edit.md
      - Reverse Geocoding: developer-guide/metadata/geocoding.md
      - Image Orientation: developer-guide/metadata/orientation.md
      - Image Classification: developer-guide/metadata/classification.md
      - Perceptual Hashes: developer-guide/metadata/perceptual-hashes.md
      - Face Recognition: developer-guide/metadata/face-recognition.md
      - Color Detection: developer-guide/metadata/colors.md
      - Camera Models: developer-guide/metadata/cameras.md
    - Web Interface:
      - Introduction: developer-guide/ui/introduction.md
      - Screenshots: developer-guide/ui/screenshots.md
      - Components: developer-guide/ui/components.md
      - Design & Colors: developer-guide/ui/design.md
      - Browsers: developer-guide/ui/browsers.md
      - Interactive Maps: developer-guide/ui/maps.md
      - Infinite Scrolling: developer-guide/ui/infinite-scrolling.md
    - Web Service API:
      - Introduction: developer-guide/api/index.md
      - Client Authentication: developer-guide/api/auth.md
      - OAuth2 Grant Types: developer-guide/api/oauth2.md
      - Search Endpoints: developer-guide/api/search.md
      - Thumbnail Images: developer-guide/api/thumbnails.md
      - Client Libraries:
        - Go: developer-guide/api/clients/go.md
    - Database Schema:
      - Introduction: developer-guide/database/index.md
      - Migrations: developer-guide/database/migrations.md
      - ER Diagram: developer-guide/database/schema.md
    - Technologies:
      - YAML: developer-guide/technologies/yaml.md
      - Golang: developer-guide/technologies/golang.md
      - TensorFlow: developer-guide/technologies/tensorflow.md
      - Docker: developer-guide/technologies/docker.md
      - Broadway: developer-guide/technologies/broadway.md
      - External APIs: developer-guide/technologies/external-apis.md
    - Security:
      - Testing Guide: developer-guide/security/index.md
      - Secure Coding in Go: developer-guide/security/go.md
      - Security Policy: developer-guide/security/policy.md
    - FAQ: developer-guide/faq.md
  - About:
    - Credits: credits.md
    - License:
      - Public License: license/agpl.md
      - Documentation: license/docs.md

extra_css:
  - css/custom.css

# External links.
extra:
  generator: false
  homepage: https://photoprism.app
  alternate:
    - name: üá¨üáß‚ÄÇEnglish
      link: /
      lang: en
    - name: üá©üá™‚ÄÇDeutsch
      link: https://docs-de.photoprism.app/
      lang: de
  social:
    - icon: fontawesome/brands/github
      link: https://link.photoprism.app/github
    - icon: fontawesome/brands/patreon
      link: https://link.photoprism.app/patreon
    - icon: material/chat
      link: https://link.photoprism.app/chat
    - icon: fontawesome/brands/twitter
      link: https://link.photoprism.app/twitter
    - icon: fontawesome/brands/mastodon
      link: https://floss.social/@photoprism
    - icon: fontawesome/brands/reddit
      link: https://link.photoprism.app/reddit
    - icon: fontawesome/brands/linkedin
      link: https://link.photoprism.app/linkedin
    - icon: material/home
      link: https://www.photoprism.app/

# Project paths.
docs_dir: docs
site_dir: site

# Project information.
site_name: PhotoPrism
site_description: Official Documentation
site_author: PhotoPrism UG
site_url: https://docs.photoprism.app/
use_directory_urls: true

# Repository information.
repo_name: photoprism/photoprism
repo_url: https://github.com/photoprism/photoprism
edit_uri: https://github.com/photoprism/photoprism-docs/tree/master/docs
copyright: 'Made with ‚ù§ in Berlin'

# Theme configuration.
theme:
  name: 'material'
  custom_dir: overrides

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.action.edit
    - content.tooltips
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
  palette:
    scheme: default
    primary: white
    accent: amber
  font:
    text: Roboto
    code: Roboto Mono
  favicon: icons/favicon.ico
  icon:
    logo: logo

plugins:
  - search
  - redirects:
      redirect_maps:
        'team.md': 'https://www.photoprism.app/about/team'
        'funding.md': 'https://www.photoprism.app/membership'
        'privacy.md': 'https://www.photoprism.app/privacy'
        'terms.md': 'https://www.photoprism.app/terms'
        'code-of-conduct.md': 'https://www.photoprism.app/code-of-conduct'
        'getting-started/freebsd.md': 'getting-started/ports/freebsd.md'
        'getting-started/first-steps.md': 'user-guide/first-steps.md'
        'user-guide/advanced/metadata.md': 'user-guide/library/metadata.md'
        'user-guide/organize/browse.md': 'user-guide/search/index.md'
        'user-guide/organize/views.md': 'user-guide/search/views.md'
        'user-guide/organize/search.md': 'user-guide/search/filters.md'
        'getting-started/advanced/https.md': 'getting-started/using-https.md'

# MkDocs extensions.
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shortener: true
      social_url_shortener: true
      normalize_issue_symbols: true
      user: 'photoprism'
      repo: 'photoprism'
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - md_in_html
  - attr_list
  - def_list
  - tables
  - abbr
  - meta
